### PR TITLE
Hotfix/chapter09 to chapter12 migration

### PR DESCRIPTION
**Pull request by RRoundTable**
## Done
- Enhanced readability of math formula from Chapter09 ~ Chapter12 (#147)
- Image migration from chapter09 to 12 (#123)

### CODE REVIEW

**Comment by Curt-Park** [comment]
How about changing the math formulation as follows?
Line81 in `10_01_Lower_Bounds_in_Linear_Programs`:

```markdown
 >$$
 >\begin{align}
 >& &{a(x+y) \geq 2a} \\\\
 >&{+} &{bx \geq 0} \\\\
 >&{+} &{cy \geq 0} \\\\
 >&{=} &{(a+b)x+(a+c)y \geq 2a} \\\\
 >&&\text{Lower bound}\ B=2a, \\
 >&&\text{for any satisfying a,b,c below}\\\\
 >& &{a + b = p}\\\\
 >& &{a + c = q}\\\\
 >& &{a,b,c \geq 0.}\\\\
 >\end{align}
 >$$
```

## AS-IS
스크린샷 2021-06-01 오후 11 25 40

## TO-BE
스크린샷 2021-06-01 오후 11 30 31

**Comment by Curt-Park** [comment]
Need to align the following math formula in `10_01_Lower_Bounds_in_Linear_Programs` as well.

스크린샷 2021-06-01 오후 11 35 27

**Comment by Curt-Park** [comment]
10-02

스크린샷 2021-06-01 오후 11 37 16

**Comment by Curt-Park** [comment]
10-05
스크린샷 2021-06-01 오후 11 40 15

**Comment by Curt-Park** [comment]
12-06 those lines are too long. We can consider new lines after (n)

스크린샷 2021-06-01 오후 11 45 02

스크린샷 2021-06-01 오후 11 45 52

스크린샷 2021-06-01 오후 11 46 48

**Comment by Curt-Park** [comment]
12-06 out of box

스크린샷 2021-06-01 오후 11 47 29

**Comment by RRoundTable** [comment]
> How about changing the math formulation as follows?
> Line81 in `10_01_Lower_Bounds_in_Linear_Programs`:
> 
> ```gfm
>  >$$
>  >\begin{align}
>  >& &{a(x+y) \geq 2a} \\\\
>  >&{+} &{bx \geq 0} \\\\
>  >&{+} &{cy \geq 0} \\\\
>  >&{=} &{(a+b)x+(a+c)y \geq 2a} \\\\
>  >&&\text{Lower bound}\ B=2a, \\
>  >&&\text{for any satisfying a,b,c below}\\\\
>  >& &{a + b = p}\\\\
>  >& &{a + c = q}\\\\
>  >& &{a,b,c \geq 0.}\\\\
>  >\end{align}
>  >$$
> ```
> 
> ## AS-IS
> 스크린샷 2021-06-01 오후 11 25 40
> 
> ## TO-BE
> 스크린샷 2021-06-01 오후 11 30 31

I think TO-BE is more readable. I will edit the latex.

**Comment by Curt-Park** [comment]
image

typo?

**Comment by RRoundTable** [comment]
> Need to align the following math formula in `10_01_Lower_Bounds_in_Linear_Programs` as well.
> 
> 스크린샷 2021-06-01 오후 11 35 27

[TO-BE]
image

**Comment by RRoundTable** [comment]
> 10-02
> 
> 스크린샷 2021-06-01 오후 11 37 16

[TO-BE]
image

**Comment by RRoundTable** [comment]
> 10-05
> 스크린샷 2021-06-01 오후 11 40 15

image

**Comment by RRoundTable** [comment]
> 12-06 those lines are too long. We can consider new lines after (n)
> 
> 스크린샷 2021-06-01 오후 11 45 02
> 
> 스크린샷 2021-06-01 오후 11 45 52
> 
> 스크린샷 2021-06-01 오후 11 46 48

## [TO-BE]

image
image
image

**Comment by RRoundTable** [comment]
> 12-06 out of the area
> 
> 스크린샷 2021-06-01 오후 11 47 29

## [TO-BE]
image

**Comment by LEEMINJOO** [comment]
11-01 장의 이미지가 아직 위키입니다.

**Comment by LEEMINJOO** [comment]
12-03 수식 정렬 수정이 필요해 보입니다.
모든 방정식이 한줄로 붙어있어 가독성이 안좋습니다.

스크린샷 2021-06-05 오후 7 41 00

**Comment by RRoundTable** [comment]
> 12-03 수식 정렬 수정이 필요해 보입니다.
> 모든 방정식이 한줄로 붙어있어 가독성이 안좋습니다.
> 
> 스크린샷 2021-06-05 오후 7 41 00

개선하였습니다.
image

**Comment by RRoundTable** [comment]
> 11-01 장의 이미지가 아직 위키입니다.

반영했습니다.

**Review by LEEMINJOO — APPROVED** [review]
고생하셨습니다

**Pull request merged**
